# Generated by Django 5.0.4 on 2024-04-20 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='inChannnel',
            new_name='inChannel',
        ),
    ]
