# Generated by Django 5.0.4 on 2024-04-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted',
            field=models.BooleanField(default=False),
        ),
    ]
