# Generated by Django 5.0.4 on 2024-04-21 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_answer_upvotes_answer_upvoted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='upvotes',
            new_name='upvoted',
        ),
    ]
